config/routes.rb
Tuurio::Application.routes.draw do

  resources :sport_clubs

  resources :ad_contacts

  resources :ad_schedules

  resources :ad_spaces

  resources :users

  resources :sport_trainers

  resources :sport_doctors

  resources :sport_facilities

  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'
  match '/home', :to => 'pages#home'
  match '/signup', :to => 'users#new'
  
  
  root :to => 'pages#home'

 resources :users

end

app/models/sport_trainer.rb
class SportTrainer < ActiveRecord::Base
  attr_accessible :address, :city, :description, :focus, :imagePath, :name, :officeHours, :phone, :plz, :price, :sportFacility, :subjectArea, :surname
end

app/controllers/sport_trainers_controller.rb
class SportTrainersController < ApplicationController
  # GET /sport_trainers
  # GET /sport_trainers.json
  def index
    @sport_trainers = SportTrainer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sport_trainers }
    end
  end

  # GET /sport_trainers/1
  # GET /sport_trainers/1.json
  def show
    @sport_trainer = SportTrainer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sport_trainer }
    end
  end

  # GET /sport_trainers/new
  # GET /sport_trainers/new.json
  def new
    @sport_trainer = SportTrainer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sport_trainer }
    end
  end

  # GET /sport_trainers/1/edit
  def edit
    @sport_trainer = SportTrainer.find(params[:id])
  end

  # POST /sport_trainers
  # POST /sport_trainers.json
  def create
    @sport_trainer = SportTrainer.new(params[:sport_trainer])

    respond_to do |format|
      if @sport_trainer.save
        format.html { redirect_to @sport_trainer, notice: 'Sport trainer was successfully created.' }
        format.json { render json: @sport_trainer, status: :created, location: @sport_trainer }
      else
        format.html { render action: "new" }
        format.json { render json: @sport_trainer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sport_trainers/1
  # PUT /sport_trainers/1.json
  def update
    @sport_trainer = SportTrainer.find(params[:id])

    respond_to do |format|
      if @sport_trainer.update_attributes(params[:sport_trainer])
        format.html { redirect_to @sport_trainer, notice: 'Sport trainer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sport_trainer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sport_trainers/1
  # DELETE /sport_trainers/1.json
  def destroy
    @sport_trainer = SportTrainer.find(params[:id])
    @sport_trainer.destroy

    respond_to do |format|
      format.html { redirect_to sport_trainers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/sport_trainers_helper.rb
module SportTrainersHelper
end

app/views/sport_trainers/_form.html.erb
<%= form_for(@sport_trainer) do |f| %>
  <% if @sport_trainer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sport_trainer.errors.count, "error") %> prohibited this sport_trainer from being saved:</h2>

      <ul>
      <% @sport_trainer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :imagePath %><br />
    <%= f.text_field :imagePath %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :surname %><br />
    <%= f.text_field :surname %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :plz %><br />
    <%= f.number_field :plz %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :officeHours %><br />
    <%= f.text_area :officeHours %>
  </div>
  <div class="field">
    <%= f.label :subjectArea %><br />
    <%= f.text_field :subjectArea %>
  </div>
  <div class="field">
    <%= f.label :focus %><br />
    <%= f.text_area :focus %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :sportFacility %><br />
    <%= f.text_field :sportFacility %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sport_trainers/edit.html.erb
<h1>Editing sport_trainer</h1>

<%= render 'form' %>

<%= link_to 'Show', @sport_trainer %> |
<%= link_to 'Back', sport_trainers_path %>

app/views/sport_trainers/index.html.erb
<h1>Listing sport_trainers</h1>

<table>
  <tr>
    <th>Imagepath</th>
    <th>Name</th>
    <th>Surname</th>
    <th>Description</th>
    <th>Address</th>
    <th>Plz</th>
    <th>City</th>
    <th>Price</th>
    <th>Officehours</th>
    <th>Subjectarea</th>
    <th>Focus</th>
    <th>Phone</th>
    <th>Sportfacility</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sport_trainers.each do |sport_trainer| %>
  <tr>
    <td><%= sport_trainer.imagePath %></td>
    <td><%= sport_trainer.name %></td>
    <td><%= sport_trainer.surname %></td>
    <td><%= sport_trainer.description %></td>
    <td><%= sport_trainer.address %></td>
    <td><%= sport_trainer.plz %></td>
    <td><%= sport_trainer.city %></td>
    <td><%= sport_trainer.price %></td>
    <td><%= sport_trainer.officeHours %></td>
    <td><%= sport_trainer.subjectArea %></td>
    <td><%= sport_trainer.focus %></td>
    <td><%= sport_trainer.phone %></td>
    <td><%= sport_trainer.sportFacility %></td>
    <td><%= link_to 'Show', sport_trainer %></td>
    <td><%= link_to 'Edit', edit_sport_trainer_path(sport_trainer) %></td>
    <td><%= link_to 'Destroy', sport_trainer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sport trainer', new_sport_trainer_path %>

app/views/sport_trainers/new.html.erb
<h1>New sport_trainer</h1>

<%= render 'form' %>

<%= link_to 'Back', sport_trainers_path %>

app/views/sport_trainers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Imagepath:</b>
  <%= @sport_trainer.imagePath %>
</p>

<p>
  <b>Name:</b>
  <%= @sport_trainer.name %>
</p>

<p>
  <b>Surname:</b>
  <%= @sport_trainer.surname %>
</p>

<p>
  <b>Description:</b>
  <%= @sport_trainer.description %>
</p>

<p>
  <b>Address:</b>
  <%= @sport_trainer.address %>
</p>

<p>
  <b>Plz:</b>
  <%= @sport_trainer.plz %>
</p>

<p>
  <b>City:</b>
  <%= @sport_trainer.city %>
</p>

<p>
  <b>Price:</b>
  <%= @sport_trainer.price %>
</p>

<p>
  <b>Officehours:</b>
  <%= @sport_trainer.officeHours %>
</p>

<p>
  <b>Subjectarea:</b>
  <%= @sport_trainer.subjectArea %>
</p>

<p>
  <b>Focus:</b>
  <%= @sport_trainer.focus %>
</p>

<p>
  <b>Phone:</b>
  <%= @sport_trainer.phone %>
</p>

<p>
  <b>Sportfacility:</b>
  <%= @sport_trainer.sportFacility %>
</p>


<%= link_to 'Edit', edit_sport_trainer_path(@sport_trainer) %> |
<%= link_to 'Back', sport_trainers_path %>