config/routes.rb
Tuurio::Application.routes.draw do

  resources :sport_clubs

  resources :ad_contacts

  resources :ad_schedules

  resources :ad_spaces

  resources :users

  resources :sport_trainers

  resources :sport_doctors

  resources :sport_facilities

  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'
  match '/home', :to => 'pages#home'
  match '/signup', :to => 'users#new'
  
  
  root :to => 'pages#home'

 resources :users

end

app/models/sport_facility.rb
class SportFacility < ActiveRecord::Base
  attr_accessible :address, :city, :description, :events, :imagePath, :name, :openingHours, :plz, :price, :sportTypes
end

app/controllers/sport_facilities_controller.rb
class SportFacilitiesController < ApplicationController
  # GET /sport_facilities
  # GET /sport_facilities.json
  def index
    @sport_facilities = SportFacility.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sport_facilities }
    end
  end

  # GET /sport_facilities/1
  # GET /sport_facilities/1.json
  def show
    @sport_facility = SportFacility.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sport_facility }
    end
  end

  # GET /sport_facilities/new
  # GET /sport_facilities/new.json
  def new
    @sport_facility = SportFacility.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sport_facility }
    end
  end

  # GET /sport_facilities/1/edit
  def edit
    @sport_facility = SportFacility.find(params[:id])
  end

  # POST /sport_facilities
  # POST /sport_facilities.json
  def create
    @sport_facility = SportFacility.new(params[:sport_facility])

    respond_to do |format|
      if @sport_facility.save
        format.html { redirect_to @sport_facility, notice: 'Sport facility was successfully created.' }
        format.json { render json: @sport_facility, status: :created, location: @sport_facility }
      else
        format.html { render action: "new" }
        format.json { render json: @sport_facility.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sport_facilities/1
  # PUT /sport_facilities/1.json
  def update
    @sport_facility = SportFacility.find(params[:id])

    respond_to do |format|
      if @sport_facility.update_attributes(params[:sport_facility])
        format.html { redirect_to @sport_facility, notice: 'Sport facility was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sport_facility.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sport_facilities/1
  # DELETE /sport_facilities/1.json
  def destroy
    @sport_facility = SportFacility.find(params[:id])
    @sport_facility.destroy

    respond_to do |format|
      format.html { redirect_to sport_facilities_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/sport_facilities_helper.rb
module SportFacilitiesHelper
end

app/views/sport_facilities/_form.html.erb
<%= form_for(@sport_facility) do |f| %>
<% if @sport_facility.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@sport_facility.errors.count, "error") %> prohibited this sport_facility from being saved:</h2>

	<ul>
		<% @sport_facility.errors.full_messages.each do |msg| %>
		<li>
			<%= msg %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>

<div>
	<div class="contentHeader">
		<div class="contentHeaderMain">
			<div class="contentHeaderPicture">
				<%= link_to( image_tag("user.png", :alt => "Picture", :class => "pictures"), "#") %>
			</div>
			<div class="contentHeaderField">
				<div class="contentHeaderCoreData">
					<%= f.label :name %>
					<%= f.text_field :name %>
				</div>
				<div class="contentHeaderCoreData">
					<%= f.label :sportTypes %>
					<%= f.text_field :sportTypes %>
				</div>
			</div>
		</div>
		<div class="contentHeaderSubmit">
			<%= f.submit %>
		</div>
	</div>
	<div class="contentForm">
		<div class="contentFormX1">
			<div class="contentField">
				<%= f.label :description %>
				<br />
				<%= f.text_field :description %>
			</div>
			<div class="contentField">
				<%= f.label :address %>
				<br />
				<%= f.text_field :address %>
			</div>
			<div class="contentField">
				<%= f.label :plz %>
				<br />
				<%= f.text_field :plz %>
			</div>
			<div class="contentField">
				<%= f.label :city %>
				<br />
				<%= f.text_field :city %>
			</div>
		</div>
		<div class="contentFormX2">
			<div class="contentField">
				<%= f.label :price %>
				<br />
				<%= f.text_field :price %>
			</div>
			<div class="contentField">
				<%= f.label :openingHours %>
				<br />
				<%= f.text_field :openingHours %>
			</div>
			<div class="contentField">
				<%= f.label :events %>
				<br />
				<%= f.text_field :events %>
			</div>
		</div>
	</div>
</div>

<% end %>

app/views/sport_facilities/edit.html.erb
<h1>Editing sport_facility</h1>

<%= render 'form' %>

<%= link_to 'Show', @sport_facility %> |
<%= link_to 'Back', sport_facilities_path %>

app/views/sport_facilities/index.html.erb
<h1>Listing sport_facilities</h1>

<table>
  <tr>
    <th>Imagepath</th>
    <th>Name</th>
    <th>Description</th>
    <th>Address</th>
    <th>Plz</th>
    <th>City</th>
    <th>Price</th>
    <th>Openinghours</th>
    <th>Sporttypes</th>
    <th>Events</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sport_facilities.each do |sport_facility| %>
  <tr>
    <td><%= sport_facility.imagePath %></td>
    <td><%= sport_facility.name %></td>
    <td><%= sport_facility.description %></td>
    <td><%= sport_facility.address %></td>
    <td><%= sport_facility.plz %></td>
    <td><%= sport_facility.city %></td>
    <td><%= sport_facility.price %></td>
    <td><%= sport_facility.openingHours %></td>
    <td><%= sport_facility.sportTypes %></td>
    <td><%= sport_facility.events %></td>
    <td><%= link_to 'Show', sport_facility %></td>
    <td><%= link_to 'Edit', edit_sport_facility_path(sport_facility) %></td>
    <td><%= link_to 'Destroy', sport_facility, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sport facility', new_sport_facility_path %>

app/views/sport_facilities/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', sport_facilities_path %>

app/views/sport_facilities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Imagepath:</b>
  <%= @sport_facility.imagePath %>
</p>

<p>
  <b>Name:</b>
  <%= @sport_facility.name %>
</p>

<p>
  <b>Description:</b>
  <%= @sport_facility.description %>
</p>

<p>
  <b>Address:</b>
  <%= @sport_facility.address %>
</p>

<p>
  <b>Plz:</b>
  <%= @sport_facility.plz %>
</p>

<p>
  <b>City:</b>
  <%= @sport_facility.city %>
</p>

<p>
  <b>Price:</b>
  <%= @sport_facility.price %>
</p>

<p>
  <b>Openinghours:</b>
  <%= @sport_facility.openingHours %>
</p>

<p>
  <b>Sporttypes:</b>
  <%= @sport_facility.sportTypes %>
</p>

<p>
  <b>Events:</b>
  <%= @sport_facility.events %>
</p>


<%= link_to 'Edit', edit_sport_facility_path(@sport_facility) %> |
<%= link_to 'Back', sport_facilities_path %>