config/routes.rb
Tuurio::Application.routes.draw do

  resources :sport_clubs

  resources :ad_contacts

  resources :ad_schedules

  resources :ad_spaces

  resources :users

  resources :sport_trainers

  resources :sport_doctors

  resources :sport_facilities

  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'
  match '/home', :to => 'pages#home'
  match '/signup', :to => 'users#new'
  
  
  root :to => 'pages#home'

 resources :users

end

app/models/ad_schedule.rb
class AdSchedule < ActiveRecord::Base
  attr_accessible :company, :contact, :description, :duration, :imagePath, :price, :size, :subjectArea, :timeShift
end

app/controllers/ad_schedules_controller.rb
class AdSchedulesController < ApplicationController
  # GET /ad_schedules
  # GET /ad_schedules.json
  def index
    @ad_schedules = AdSchedule.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ad_schedules }
    end
  end

  # GET /ad_schedules/1
  # GET /ad_schedules/1.json
  def show
    @ad_schedule = AdSchedule.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ad_schedule }
    end
  end

  # GET /ad_schedules/new
  # GET /ad_schedules/new.json
  def new
    @ad_schedule = AdSchedule.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ad_schedule }
    end
  end

  # GET /ad_schedules/1/edit
  def edit
    @ad_schedule = AdSchedule.find(params[:id])
  end

  # POST /ad_schedules
  # POST /ad_schedules.json
  def create
    @ad_schedule = AdSchedule.new(params[:ad_schedule])

    respond_to do |format|
      if @ad_schedule.save
        format.html { redirect_to @ad_schedule, notice: 'Ad schedule was successfully created.' }
        format.json { render json: @ad_schedule, status: :created, location: @ad_schedule }
      else
        format.html { render action: "new" }
        format.json { render json: @ad_schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ad_schedules/1
  # PUT /ad_schedules/1.json
  def update
    @ad_schedule = AdSchedule.find(params[:id])

    respond_to do |format|
      if @ad_schedule.update_attributes(params[:ad_schedule])
        format.html { redirect_to @ad_schedule, notice: 'Ad schedule was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ad_schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ad_schedules/1
  # DELETE /ad_schedules/1.json
  def destroy
    @ad_schedule = AdSchedule.find(params[:id])
    @ad_schedule.destroy

    respond_to do |format|
      format.html { redirect_to ad_schedules_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/ad_schedules_helper.rb
module AdSchedulesHelper
end

app/views/ad_schedules/_form.html.erb
<%= form_for(@ad_schedule) do |f| %>
  <% if @ad_schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ad_schedule.errors.count, "error") %> prohibited this ad_schedule from being saved:</h2>

      <ul>
      <% @ad_schedule.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :imagePath %><br />
    <%= f.text_field :imagePath %>
  </div>
  <div class="field">
    <%= f.label :company %><br />
    <%= f.text_field :company %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :contact %><br />
    <%= f.text_field :contact %>
  </div>
  <div class="field">
    <%= f.label :subjectArea %><br />
    <%= f.text_field :subjectArea %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :duration %><br />
    <%= f.number_field :duration %>
  </div>
  <div class="field">
    <%= f.label :size %><br />
    <%= f.text_field :size %>
  </div>
  <div class="field">
    <%= f.label :timeShift %><br />
    <%= f.number_field :timeShift %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ad_schedules/edit.html.erb
<h1>Editing ad_schedule</h1>

<%= render 'form' %>

<%= link_to 'Show', @ad_schedule %> |
<%= link_to 'Back', ad_schedules_path %>

app/views/ad_schedules/index.html.erb
<h1>Listing ad_schedules</h1>

<table>
  <tr>
    <th>Imagepath</th>
    <th>Company</th>
    <th>Description</th>
    <th>Contact</th>
    <th>Subjectarea</th>
    <th>Price</th>
    <th>Duration</th>
    <th>Size</th>
    <th>Timeshift</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ad_schedules.each do |ad_schedule| %>
  <tr>
    <td><%= ad_schedule.imagePath %></td>
    <td><%= ad_schedule.company %></td>
    <td><%= ad_schedule.description %></td>
    <td><%= ad_schedule.contact %></td>
    <td><%= ad_schedule.subjectArea %></td>
    <td><%= ad_schedule.price %></td>
    <td><%= ad_schedule.duration %></td>
    <td><%= ad_schedule.size %></td>
    <td><%= ad_schedule.timeShift %></td>
    <td><%= link_to 'Show', ad_schedule %></td>
    <td><%= link_to 'Edit', edit_ad_schedule_path(ad_schedule) %></td>
    <td><%= link_to 'Destroy', ad_schedule, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Ad schedule', new_ad_schedule_path %>

app/views/ad_schedules/new.html.erb
<h1>New ad_schedule</h1>

<%= render 'form' %>

<%= link_to 'Back', ad_schedules_path %>

app/views/ad_schedules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Imagepath:</b>
  <%= @ad_schedule.imagePath %>
</p>

<p>
  <b>Company:</b>
  <%= @ad_schedule.company %>
</p>

<p>
  <b>Description:</b>
  <%= @ad_schedule.description %>
</p>

<p>
  <b>Contact:</b>
  <%= @ad_schedule.contact %>
</p>

<p>
  <b>Subjectarea:</b>
  <%= @ad_schedule.subjectArea %>
</p>

<p>
  <b>Price:</b>
  <%= @ad_schedule.price %>
</p>

<p>
  <b>Duration:</b>
  <%= @ad_schedule.duration %>
</p>

<p>
  <b>Size:</b>
  <%= @ad_schedule.size %>
</p>

<p>
  <b>Timeshift:</b>
  <%= @ad_schedule.timeShift %>
</p>


<%= link_to 'Edit', edit_ad_schedule_path(@ad_schedule) %> |
<%= link_to 'Back', ad_schedules_path %>